import { mkdir, rm, writeFile } from "node:fs/promises";
import { UWDATA_COMMIT } from "../../src/sources/uwdata/source";
import type { FullChunk, HueChunk, LanguageCoverage } from "../../src/engine/types";
import {
  download,
  parseBasicInfo,
  parseFullBinned,
  parseHueBinned,
  type RawBasicRow,
  type RawFullRecord,
  type RawHueTerm,
} from "./fetch";
import {
  FULL_BIN_SIZE,
  HUE_BIN_COUNT,
  buildFullChunk,
  buildHueChunk,
  chunkCoverage,
} from "./transform";

export const FULL_LANGS = [
  "de", "en", "es", "fa", "fi", "fr", "ko", "nl", "pl", "pt", "ro", "ru", "sv", "zh",
];

export const HUE_LANGS = [
  "ar", "bg", "ca", "cs", "da", "el", "et", "he", "hi", "hr", "hu", "id", "it", "ja",
  "ka", "lt", "mk", "ms", "nb", "sk", "sl", "sr", "th", "tr", "uk", "ur", "vi",
];

const FULL_PATH = "model/binned_full_colors/full_color_names_binned_0.05.json";
const HUE_PATH = "model/binned_hue_colors/hue_color_names_binned_72.json";
const BASIC_PATH = (lang: string) => `model/color_info_by_lang/basic_colors_info_${lang}.csv`;

const DATA_DIR = new URL("../../src/data/uwdata/", import.meta.url);
const MANIFEST_PATH = new URL("../../src/sources/uwdata/chunks.ts", import.meta.url);

export interface SyncInputs {
  full: RawFullRecord[];
  hue: Record<string, Record<string, RawHueTerm>>;
  centroids: Map<string, RawBasicRow[]>;
}

export interface SyncMeta {
  source: "uwdata";
  commitSha: string;
  generatedAt: string;
  binSize: number;
  hueBinCount: number;
  languages: Record<string, LanguageCoverage>;
}

export interface SyncOutput {
  chunks: Map<string, FullChunk | HueChunk>;
  meta: SyncMeta;
}

export function buildOutput(inputs: SyncInputs, generatedAt: string): SyncOutput {
  const chunks = new Map<string, FullChunk | HueChunk>();
  const languages: Record<string, LanguageCoverage> = {};

  const byLang = new Map<string, RawFullRecord[]>();
  for (const record of inputs.full) {
    if (!FULL_LANGS.includes(record.langAbv)) continue;
    const bucket = byLang.get(record.langAbv);
    if (bucket === undefined) byLang.set(record.langAbv, [record]);
    else bucket.push(record);
  }

  for (const [lang, records] of byLang) {
    const chunk = buildFullChunk(lang, records, inputs.centroids.get(lang) ?? []);
    chunks.set(lang, chunk);
    languages[lang] = chunkCoverage(chunk);
  }

  for (const [lang, terms] of Object.entries(inputs.hue)) {
    if (!HUE_LANGS.includes(lang)) continue;
    const chunk = buildHueChunk(lang, terms, inputs.centroids.get(lang) ?? []);
    chunks.set(lang, chunk);
    languages[lang] = chunkCoverage(chunk);
  }

  return {
    chunks,
    meta: {
      source: "uwdata",
      commitSha: UWDATA_COMMIT,
      generatedAt,
      binSize: FULL_BIN_SIZE,
      hueBinCount: HUE_BIN_COUNT,
      languages,
    },
  };
}

export function renderChunkModule(chunk: FullChunk | HueChunk): string {
  return [
    "// Generated by scripts/sync-uwdata. Do not edit by hand.",
    `export default ${JSON.stringify(chunk, null, 2)};`,
    "",
  ].join("\n");
}

export function renderManifest(locales: string[]): string {
  const entries = [...locales]
    .sort()
    .map(locale => `  "${locale}": () => import("../../data/uwdata/${locale}.js"),`)
    .join("\n");

  return [
    "// Generated by scripts/sync-uwdata. Do not edit by hand.",
    "import type { ChunkLoaders } from \"../../engine/types\";",
    "",
    "export const uwdataChunks: ChunkLoaders = {",
    entries,
    "};",
    "",
  ].join("\n");
}

export async function main(): Promise<void> {
  console.log(`Syncing uwdata at ${UWDATA_COMMIT}…`);

  const [fullJson, hueJson] = await Promise.all([download(FULL_PATH), download(HUE_PATH)]);
  const full = parseFullBinned(fullJson);
  const hue = parseHueBinned(hueJson);

  const centroids = new Map<string, RawBasicRow[]>();
  for (const lang of [...FULL_LANGS, ...HUE_LANGS]) {
    try {
      centroids.set(lang, parseBasicInfo(await download(BASIC_PATH(lang))));
    } catch {
      console.warn(`  no basic_colors_info for ${lang}; centroids will be null`);
    }
  }

  const output = buildOutput({ full, hue, centroids }, new Date().toISOString());

  await rm(DATA_DIR, { recursive: true, force: true });
  await mkdir(DATA_DIR, { recursive: true });

  const sizes: [string, number][] = [];
  for (const [lang, chunk] of output.chunks) {
    const source = renderChunkModule(chunk);
    await writeFile(new URL(`${lang}.js`, DATA_DIR), source, "utf8");
    sizes.push([lang, Buffer.byteLength(source, "utf8")]);
  }

  await writeFile(
    new URL("meta.json", DATA_DIR),
    `${JSON.stringify(output.meta, null, 2)}\n`,
    "utf8",
  );
  await writeFile(MANIFEST_PATH, renderManifest([...output.chunks.keys()]), "utf8");

  sizes.sort((a, b) => b[1] - a[1]);
  console.log(`\nWrote ${sizes.length} chunks:`);
  for (const [lang, bytes] of sizes) {
    const coverage = output.meta.languages[lang];
    console.log(
      `  ${lang.padEnd(4)} ${(bytes / 1024).toFixed(0).padStart(5)} KB  `
      + `${coverage?.model ?? "?"}  ${coverage?.terms ?? 0} terms  `
      + `${((coverage?.coverage ?? 0) * 100).toFixed(1)}% coverage`,
    );
  }
  console.log(`\nTotal: ${(sizes.reduce((sum, [, b]) => sum + b, 0) / 1024 / 1024).toFixed(2)} MB`);
}

if (import.meta.main) {
  await main();
}
