import { mkdir, rm, writeFile } from "node:fs/promises";
import { UWDATA_COMMIT } from "../../src/sources/uwdata/source";
import type { FullChunk, HueChunk, LanguageCoverage } from "../../src/engine/types";
import {
  download,
  parseBasicInfo,
  parseFullBinned,
  parseHueBinned,
  SchemaError,
  type RawBasicRow,
  type RawFullRecord,
  type RawHueTerm,
} from "./fetch";
import {
  FULL_BIN_SIZE,
  HUE_BIN_COUNT,
  buildFullChunk,
  buildHueChunk,
  chunkCoverage,
} from "./transform";

const UPSTREAM_REPO = "uwdata/color-naming-in-different-languages";

export const FULL_LANGS = [
  "de", "en", "es", "fa", "fi", "fr", "ko", "nl", "pl", "pt", "ro", "ru", "sv", "zh",
];

// Upstream's basic_colors_info directory lists 41 languages, but at this pinned
// commit only these 6 (beyond the 14 FULL_LANGS) actually have entries in
// hue_color_names_binned_72.json — the other 21 have centroid data only, with
// no binned name data at any granularity this package uses. Verified against
// the raw file: the 21 excluded languages are bg, ca, cs, et, he, hi, hr, id,
// ja, ka, lt, mk, ms, nb, sk, sl, sr, th, uk, ur, vi.
export const HUE_LANGS = ["ar", "da", "el", "hu", "it", "tr"];

const FULL_PATH = "model/binned_full_colors/full_color_names_binned_0.05.json";
const HUE_PATH = "model/binned_hue_colors/hue_color_names_binned_72.json";
const BASIC_PATH = (lang: string) => `model/color_info_by_lang/basic_colors_info_${lang}.csv`;

const DATA_DIR = new URL("../../src/data/uwdata/", import.meta.url);
const MANIFEST_PATH = new URL("../../src/sources/uwdata/chunks.ts", import.meta.url);

export interface SyncInputs {
  full: RawFullRecord[];
  hue: Record<string, Record<string, RawHueTerm>>;
  centroids: Map<string, RawBasicRow[]>;
}

export interface SyncMeta {
  source: "uwdata";
  commitSha: string;
  generatedAt: string;
  binSize: number;
  hueBinCount: number;
  languages: Record<string, LanguageCoverage>;
}

export interface SyncOutput {
  chunks: Map<string, FullChunk | HueChunk>;
  meta: SyncMeta;
  /**
   * Languages upstream's binned data covers that neither FULL_LANGS nor
   * HUE_LANGS lists — present in the raw input but not shipped. Never
   * auto-added: a new language ships only once a human adds it to the
   * appropriate allowlist. Sorted for stable output.
   */
  unshippedLanguages: string[];
}

export function buildOutput(
  inputs: SyncInputs,
  generatedAt: string,
  commitSha: string = UWDATA_COMMIT,
): SyncOutput {
  const chunks = new Map<string, FullChunk | HueChunk>();
  const languages: Record<string, LanguageCoverage> = {};
  const unshippedLanguages = new Set<string>();

  const byLang = new Map<string, RawFullRecord[]>();
  // A language can appear in *both* raw inputs — e.g. upstream's hue file
  // has an entry for every language, including the ones this package ships
  // via the full model instead — so "not on this list" alone doesn't mean
  // "not shipped". Only flag a language once it's on neither allowlist.
  const shippedLangs = new Set([...FULL_LANGS, ...HUE_LANGS]);

  for (const record of inputs.full) {
    if (!FULL_LANGS.includes(record.langAbv)) {
      if (!shippedLangs.has(record.langAbv)) unshippedLanguages.add(record.langAbv);
      continue;
    }
    const bucket = byLang.get(record.langAbv);
    if (bucket === undefined) byLang.set(record.langAbv, [record]);
    else bucket.push(record);
  }

  for (const [lang, records] of byLang) {
    const chunk = buildFullChunk(lang, records, inputs.centroids.get(lang) ?? []);
    chunks.set(lang, chunk);
    languages[lang] = chunkCoverage(chunk);
  }

  for (const [lang, terms] of Object.entries(inputs.hue)) {
    if (!HUE_LANGS.includes(lang)) {
      if (!shippedLangs.has(lang)) unshippedLanguages.add(lang);
      continue;
    }
    const chunk = buildHueChunk(lang, terms, inputs.centroids.get(lang) ?? []);
    chunks.set(lang, chunk);
    languages[lang] = chunkCoverage(chunk);
  }

  return {
    chunks,
    meta: {
      source: "uwdata",
      commitSha,
      generatedAt,
      binSize: FULL_BIN_SIZE,
      hueBinCount: HUE_BIN_COUNT,
      languages,
    },
    unshippedLanguages: [...unshippedLanguages].sort(),
  };
}

export function renderChunkModule(chunk: FullChunk | HueChunk, commitSha: string = UWDATA_COMMIT): string {
  return [
    "// Generated by scripts/sync-uwdata. Do not edit by hand.",
    "//",
    "// Colour-name data derived from:",
    "//   https://github.com/uwdata/color-naming-in-different-languages",
    `//   at commit ${commitSha}`,
    "//",
    "// Kim, Y., Thayer, K., Silva Gorsky, G., & Heer, J. (2019). Color Names Across",
    "// Languages: Salient Colors and Term Translation in Multilingual Color Naming",
    "// Models. EuroVis.",
    `export default ${JSON.stringify(chunk)};`,
    "",
  ].join("\n");
}

export function renderManifest(locales: string[]): string {
  const entries = [...locales]
    .sort()
    .map(locale => (
      `  "${locale}": () => import("../../data/uwdata/${locale}.js") as unknown as Promise<{ default: Chunk }>,`
    ))
    .join("\n");

  return [
    "// Generated by scripts/sync-uwdata. Do not edit by hand.",
    "//",
    "// The chunk .js files below are produced by this same script's validated transform,",
    "// so asserting their shape here (rather than trusting allowJs inference, which widens",
    "// literal/tuple types to string/array and does not \"sufficiently overlap\" with Chunk)",
    "// is honest and keeps the manifest type-checking.",
    "import type { Chunk, ChunkLoaders } from \"../../engine/types\";",
    "",
    "export const uwdataChunks: ChunkLoaders = {",
    entries,
    "};",
    "",
  ].join("\n");
}

/**
 * `true` when `error` came from {@link download} reporting a 404 — i.e. the
 * language genuinely has no `basic_colors_info` upstream. Any other error
 * (network failure, 5xx, schema drift) is a real problem the caller must not
 * silently swallow.
 */
export function isMissingUpstreamFile(error: unknown): boolean {
  return error instanceof SchemaError && error.status === 404;
}

/**
 * Parses `--ref <ref>` from CLI args, defaulting to `UWDATA_COMMIT` so a
 * bare `sync:uwdata` keeps today's pinned, reproducible behaviour.
 */
export function parseArgs(argv: string[]): { ref: string } {
  const index = argv.indexOf("--ref");
  if (index === -1) return { ref: UWDATA_COMMIT };

  const ref = argv[index + 1];
  if (ref === undefined) throw new Error("--ref requires a value, e.g. --ref master.");
  return { ref };
}

/**
 * Resolves a git ref (branch, tag, or sha) to a concrete commit sha via the
 * GitHub API, so a `--ref master` sync downloads every file from the exact
 * same commit even if upstream's `master` moves mid-run.
 */
export async function resolveRef(ref: string): Promise<string> {
  const url = `https://api.github.com/repos/${UPSTREAM_REPO}/commits/${encodeURIComponent(ref)}`;
  const response = await fetch(url, { headers: { Accept: "application/vnd.github+json" } });
  if (!response.ok) {
    throw new SchemaError(`Failed to resolve ref "${ref}" to a commit sha: HTTP ${response.status}`, response.status);
  }

  const body: unknown = await response.json();
  const sha = typeof body === "object" && body !== null
    ? (body as Record<string, unknown>).sha
    : undefined;
  if (typeof sha !== "string" || sha.length === 0) {
    throw new SchemaError(`GitHub API response for ref "${ref}" did not include a sha.`);
  }
  return sha;
}

export async function main(argv: string[] = process.argv.slice(2)): Promise<void> {
  const { ref } = parseArgs(argv);
  console.log(`Resolving ref "${ref}"…`);
  const commitSha = await resolveRef(ref);
  console.log(`\n=== Syncing uwdata at ${commitSha} (ref "${ref}") ===\n`);

  const [fullJson, hueJson] = await Promise.all([
    download(FULL_PATH, commitSha),
    download(HUE_PATH, commitSha),
  ]);
  const full = parseFullBinned(fullJson);
  const hue = parseHueBinned(hueJson);

  const centroids = new Map<string, RawBasicRow[]>();
  const centroidFailures: { lang: string; message: string }[] = [];
  for (const lang of [...FULL_LANGS, ...HUE_LANGS]) {
    try {
      centroids.set(lang, parseBasicInfo(await download(BASIC_PATH(lang), commitSha)));
    } catch (error) {
      if (isMissingUpstreamFile(error)) {
        console.warn(`  no basic_colors_info for ${lang}; centroids will be null`);
      } else {
        const message = error instanceof Error ? error.message : String(error);
        console.error(`  failed to sync basic_colors_info for ${lang}: ${message}`);
        centroidFailures.push({ lang, message });
      }
    }
  }

  if (centroidFailures.length > 0) {
    console.error(
      `\n${centroidFailures.length} language(s) failed to sync centroids `
      + "(not merely absent upstream):",
    );
    for (const { lang, message } of centroidFailures) {
      console.error(`  ${lang}: ${message}`);
    }
    console.error("\nAborting without writing any output.");
    process.exit(1);
  }

  const output = buildOutput({ full, hue, centroids }, new Date().toISOString(), commitSha);

  // Render everything into memory before touching disk, so a failure in
  // rendering (which should never happen for well-formed chunks, but might
  // for a future data shape) can't leave DATA_DIR half-deleted while the
  // manifest still references the languages that used to live there.
  const chunkSources = new Map<string, string>();
  for (const [lang, chunk] of output.chunks) {
    chunkSources.set(lang, renderChunkModule(chunk, commitSha));
  }
  const manifestSource = renderManifest([...output.chunks.keys()]);
  const metaSource = `${JSON.stringify(output.meta, null, 2)}\n`;

  await rm(DATA_DIR, { recursive: true, force: true });
  await mkdir(DATA_DIR, { recursive: true });

  const sizes: [string, number][] = [];
  for (const [lang, source] of chunkSources) {
    await writeFile(new URL(`${lang}.js`, DATA_DIR), source, "utf8");
    sizes.push([lang, Buffer.byteLength(source, "utf8")]);
  }

  await writeFile(new URL("meta.json", DATA_DIR), metaSource, "utf8");
  await writeFile(MANIFEST_PATH, manifestSource, "utf8");

  sizes.sort((a, b) => b[1] - a[1]);
  console.log(`\nWrote ${sizes.length} chunks:`);
  for (const [lang, bytes] of sizes) {
    const coverage = output.meta.languages[lang];
    console.log(
      `  ${lang.padEnd(4)} ${(bytes / 1024).toFixed(0).padStart(5)} KB  `
      + `${coverage?.model ?? "?"}  ${coverage?.terms ?? 0} terms  `
      + `${((coverage?.coverage ?? 0) * 100).toFixed(1)}% coverage`,
    );
  }
  console.log(`\nTotal: ${(sizes.reduce((sum, [, b]) => sum + b, 0) / 1024 / 1024).toFixed(2)} MB`);
  console.log(`\nResolved commit sha: ${commitSha}`);

  if (output.unshippedLanguages.length > 0) {
    console.log("\n=== NEW UPSTREAM LANGUAGES NOT SHIPPED ===");
    console.log(
      "Upstream has binned name data for these languages, but they aren't in "
      + "FULL_LANGS or HUE_LANGS (scripts/sync-uwdata/main.ts), so nothing was "
      + "written for them. Add a language to the appropriate allowlist if it "
      + "should ship — this is a human decision, not automated.",
    );
    for (const lang of output.unshippedLanguages) console.log(`  ${lang}`);
    console.log("===========================================\n");
  }
}

if (import.meta.main) {
  await main();
}
