import { describe, expect, it } from "bun:test";
import { parseBasicInfo, parseFullBinned, parseHueBinned } from "../../scripts/sync-uwdata/fetch";
import { buildOutput, renderChunkModule, renderManifest } from "../../scripts/sync-uwdata/main";

const fixture = (name: string) => Bun.file(`${import.meta.dir}/../fixtures/uwdata/${name}`).text();

async function inputs() {
  const ko = parseBasicInfo(await fixture("basic_colors_info_ko.csv"));
  return {
    full: parseFullBinned(await fixture("full_colors_binned.json")),
    hue: parseHueBinned(await fixture("hue_colors_binned.json")),
    centroids: new Map([["ko", ko]]),
  };
}

describe("buildOutput", () => {
  it("emits one chunk per language present in the inputs", async () => {
    const output = buildOutput(await inputs(), "2026-07-19T00:00:00.000Z");
    expect([...output.chunks.keys()].sort()).toEqual(["ar", "en", "ko"]);
    expect(output.chunks.get("ko")?.model).toBe("full");
    expect(output.chunks.get("ar")?.model).toBe("hue");
  });

  it("records pinned revision and per-language coverage in meta", async () => {
    const output = buildOutput(await inputs(), "2026-07-19T00:00:00.000Z");
    expect(output.meta.commitSha).toBe("f0d3e30db9e4b2c3b703bde0d816043eb48a6cb5");
    expect(output.meta.generatedAt).toBe("2026-07-19T00:00:00.000Z");
    expect(output.meta.languages.ko?.model).toBe("full");
    expect(output.meta.languages.ko?.terms).toBe(2);
  });

  it("ignores languages outside the declared model lists", async () => {
    const base = await inputs();
    const output = buildOutput(
      { ...base, full: [...base.full, { ...base.full[0]!, langAbv: "zz" }] },
      "2026-07-19T00:00:00.000Z",
    );
    expect(output.chunks.has("zz")).toBe(false);
  });
});

describe("renderChunkModule", () => {
  it("emits a default-exporting ES module", async () => {
    const output = buildOutput(await inputs(), "2026-07-19T00:00:00.000Z");
    const source = renderChunkModule(output.chunks.get("ko")!);
    expect(source).toStartWith("// Generated by scripts/sync-uwdata");
    expect(source).toContain("export default");
    expect(source).toContain("\"model\": \"full\"");
  });
});

describe("renderManifest", () => {
  it("emits a static lazy-import map", () => {
    const source = renderManifest(["ko", "ar"]);
    expect(source).toContain("\"ko\": () => import(\"../../data/uwdata/ko.js\")");
    expect(source).toContain("\"ar\": () => import(\"../../data/uwdata/ar.js\")");
  });
});
