import { describe, expect, it } from "bun:test";
import { parseBasicInfo, parseFullBinned, parseHueBinned, SchemaError } from "../../scripts/sync-uwdata/fetch";
import {
  buildOutput,
  isMissingUpstreamFile,
  renderChunkModule,
  renderManifest,
} from "../../scripts/sync-uwdata/main";

const fixture = (name: string) => Bun.file(`${import.meta.dir}/../fixtures/uwdata/${name}`).text();

async function inputs() {
  const ko = parseBasicInfo(await fixture("basic_colors_info_ko.csv"));
  return {
    full: parseFullBinned(await fixture("full_colors_binned.json")),
    hue: parseHueBinned(await fixture("hue_colors_binned.json")),
    centroids: new Map([["ko", ko]]),
  };
}

describe("buildOutput", () => {
  it("emits one chunk per language present in the inputs", async () => {
    const output = buildOutput(await inputs(), "2026-07-19T00:00:00.000Z");
    expect([...output.chunks.keys()].sort()).toEqual(["ar", "en", "ko"]);
    expect(output.chunks.get("ko")?.model).toBe("full");
    expect(output.chunks.get("ar")?.model).toBe("hue");
  });

  it("records pinned revision and per-language coverage in meta", async () => {
    const output = buildOutput(await inputs(), "2026-07-19T00:00:00.000Z");
    expect(output.meta.commitSha).toBe("f0d3e30db9e4b2c3b703bde0d816043eb48a6cb5");
    expect(output.meta.generatedAt).toBe("2026-07-19T00:00:00.000Z");
    expect(output.meta.languages.ko?.model).toBe("full");
    expect(output.meta.languages.ko?.terms).toBe(2);
  });

  it("ignores languages outside the declared model lists", async () => {
    const base = await inputs();
    const output = buildOutput(
      { ...base, full: [...base.full, { ...base.full[0]!, langAbv: "zz" }] },
      "2026-07-19T00:00:00.000Z",
    );
    expect(output.chunks.has("zz")).toBe(false);
  });
});

describe("renderChunkModule", () => {
  it("emits a default-exporting ES module", async () => {
    const output = buildOutput(await inputs(), "2026-07-19T00:00:00.000Z");
    const source = renderChunkModule(output.chunks.get("ko")!);
    expect(source).toStartWith("// Generated by scripts/sync-uwdata");
    expect(source).toContain("export default");
    expect(source).toContain("\"model\":\"full\"");
  });

  it("serializes chunks compactly without whitespace", async () => {
    const output = buildOutput(await inputs(), "2026-07-19T00:00:00.000Z");
    const source = renderChunkModule(output.chunks.get("ko")!);
    // Compactness matters: pretty-printed output would inflate shipped data files by ~2.5×.
    expect(source).not.toContain("\n  ");
  });
});

describe("renderManifest", () => {
  it("emits a static lazy-import map", () => {
    const source = renderManifest(["ko", "ar"]);
    expect(source).toContain("\"ko\": () => import(\"../../data/uwdata/ko.js\")");
    expect(source).toContain("\"ar\": () => import(\"../../data/uwdata/ar.js\")");
  });

  it("asserts each loader's resolved type, since allowJs inference of the", () => {
    // generated .js chunks widens literal/tuple types and would otherwise
    // fail to type-check against ChunkLoaders (see Chunk in engine/types).
    const source = renderManifest(["ko"]);
    expect(source).toContain(
      "\"ko\": () => import(\"../../data/uwdata/ko.js\") as unknown as Promise<{ default: Chunk }>,",
    );
    expect(source).toContain("import type { Chunk, ChunkLoaders } from \"../../engine/types\";");
  });
});

describe("isMissingUpstreamFile", () => {
  it("is true for a SchemaError with a 404 status", () => {
    expect(isMissingUpstreamFile(new SchemaError("not found", 404))).toBe(true);
  });

  it("is false for a SchemaError with a non-404 status", () => {
    expect(isMissingUpstreamFile(new SchemaError("server error", 500))).toBe(false);
  });

  it("is false for a SchemaError with no status (schema drift, not HTTP)", () => {
    expect(isMissingUpstreamFile(new SchemaError("missing column"))).toBe(false);
  });

  it("is false for a non-SchemaError error", () => {
    expect(isMissingUpstreamFile(new TypeError("network error"))).toBe(false);
  });

  it("is false for a non-error thrown value", () => {
    expect(isMissingUpstreamFile("nope")).toBe(false);
  });
});
