declare module "culori/fn" {
  const _default: any;
  export default _default;
  export type CuloriColor = any;
  export type ModeDefinition = any;
  export const parse: any;
  export const converter: any;
  export const formatCss: any;
  export const formatHex: any;
  export const toGamut: any;
  export const getMode: any;
  export const interpolate: any;
  export const useMode: any;
  export const clampChroma: any;
  export const displayable: any;
  export const formatRgb: any;
  export const formatHsl: any;
  export const wcagContrast: any;
  export const differenceCie76: any;
  export const nearest: any;
  export const modeA98: any;
  export const modeHsl: any;
  export const modeHsv: any;
  export const modeHwb: any;
  export const modeLab: any;
  export const modeLab65: any;
  export const modeLch: any;
  export const modeLchab: any;
  export const modeLrgb: any;
  export const modeOkhsl: any;
  export const modeOkhsv: any;
  export const modeOklab: any;
  export const modeOklch: any;
  export const modeP3: any;
  export const modeProphoto: any;
  export const modeRec2020: any;
  export const modeRgb: any;
  export const modeXyz50: any;
  export const modeXyz65: any;
}
