// Generated by scripts/sync-uwdata. Do not edit by hand.
//
// The chunk .js files below are produced by this same script's validated transform,
// so asserting their shape here (rather than trusting allowJs inference, which widens
// literal/tuple types to string/array and does not "sufficiently overlap" with Chunk)
// is honest and keeps the manifest type-checking.
import type { Chunk, ChunkLoaders } from "../../engine/types";

export const uwdataChunks: ChunkLoaders = {
  "ar": () => import("../../data/uwdata/ar.js") as unknown as Promise<{ default: Chunk }>,
  "da": () => import("../../data/uwdata/da.js") as unknown as Promise<{ default: Chunk }>,
  "de": () => import("../../data/uwdata/de.js") as unknown as Promise<{ default: Chunk }>,
  "el": () => import("../../data/uwdata/el.js") as unknown as Promise<{ default: Chunk }>,
  "en": () => import("../../data/uwdata/en.js") as unknown as Promise<{ default: Chunk }>,
  "es": () => import("../../data/uwdata/es.js") as unknown as Promise<{ default: Chunk }>,
  "fa": () => import("../../data/uwdata/fa.js") as unknown as Promise<{ default: Chunk }>,
  "fi": () => import("../../data/uwdata/fi.js") as unknown as Promise<{ default: Chunk }>,
  "fr": () => import("../../data/uwdata/fr.js") as unknown as Promise<{ default: Chunk }>,
  "hu": () => import("../../data/uwdata/hu.js") as unknown as Promise<{ default: Chunk }>,
  "it": () => import("../../data/uwdata/it.js") as unknown as Promise<{ default: Chunk }>,
  "ko": () => import("../../data/uwdata/ko.js") as unknown as Promise<{ default: Chunk }>,
  "nl": () => import("../../data/uwdata/nl.js") as unknown as Promise<{ default: Chunk }>,
  "pl": () => import("../../data/uwdata/pl.js") as unknown as Promise<{ default: Chunk }>,
  "pt": () => import("../../data/uwdata/pt.js") as unknown as Promise<{ default: Chunk }>,
  "ro": () => import("../../data/uwdata/ro.js") as unknown as Promise<{ default: Chunk }>,
  "ru": () => import("../../data/uwdata/ru.js") as unknown as Promise<{ default: Chunk }>,
  "sv": () => import("../../data/uwdata/sv.js") as unknown as Promise<{ default: Chunk }>,
  "tr": () => import("../../data/uwdata/tr.js") as unknown as Promise<{ default: Chunk }>,
  "zh": () => import("../../data/uwdata/zh.js") as unknown as Promise<{ default: Chunk }>,
};
