// Generated by scripts/sync-ral. Do not edit by hand.
//
// RAL Classic codes and sRGB values from ieskudero/ral-colors (MIT).
//
// RAL is a trademark of RAL gGmbH. These are factual colour values, not
// the RAL system itself, and this package is neither affiliated with nor
// endorsed by RAL gGmbH.
import type { Chunk, ChunkLoaders } from "../../engine/types";

export const ralChunks: ChunkLoaders = {
  "und": () => import("../../data/ral/und.js") as unknown as Promise<{ default: Chunk }>,
};
