import { mkdir, rm, writeFile } from "node:fs/promises";
import type { LanguageCoverage, PaletteChunk } from "../../src/engine/types";
import { fetchPantone } from "./fetch";
import { NEUTRAL_LOCALE, buildPantoneChunk } from "./transform";

const DATA_DIR = new URL("../../src/data/pantone/", import.meta.url);
const SOURCE_DIR = new URL("../../src/sources/pantone/", import.meta.url);
const MANIFEST_PATH = new URL("chunks.ts", SOURCE_DIR);

const ATTRIBUTION = [
  "// Generated by scripts/sync-pantone. Do not edit by hand.",
  "//",
  "// Pantone Fashion, Home + Interiors (TCX/TPG) numbers, names and sRGB",
  "// values from Margaret2/pantone-colors, which declares no licence and",
  "// states that the names are Pantone copyright while the hex values are",
  "// published freely on pantone.com.",
  "//",
  "// PANTONE is a trademark of Pantone LLC. This package is neither",
  "// affiliated with nor endorsed by Pantone LLC.",
];

export interface PantoneMeta {
  source: "pantone";
  retrievedAt: string;
  itemCount: number;
  languages: Record<string, LanguageCoverage>;
}

export function buildMeta(chunk: PaletteChunk, retrievedAt: string): PantoneMeta {
  return {
    source: "pantone",
    retrievedAt,
    itemCount: chunk.terms.length,
    // A catalogue names its own catalogue entirely, so coverage is 1 by
    // construction rather than a measured fraction.
    languages: { [NEUTRAL_LOCALE]: { model: "palette", terms: chunk.terms.length, coverage: 1 } },
  };
}

export function renderChunkModule(chunk: PaletteChunk): string {
  return [...ATTRIBUTION, `export default ${JSON.stringify(chunk)};`, ""].join("\n");
}

export function renderManifest(): string {
  return [
    ...ATTRIBUTION,
    "import type { Chunk, ChunkLoaders } from \"../../engine/types\";",
    "",
    "export const pantoneChunks: ChunkLoaders = {",
    `  "${NEUTRAL_LOCALE}": () => import("../../data/pantone/${NEUTRAL_LOCALE}.js") as unknown as Promise<{ default: Chunk }>,`,
    "};",
    "",
  ].join("\n");
}

export async function main(): Promise<void> {
  console.log("Fetching Pantone data…");
  const rows = await fetchPantone();
  const chunk = buildPantoneChunk(rows);
  const meta = buildMeta(chunk, new Date().toISOString());

  // Render everything into memory before touching disk, so a rendering failure
  // cannot leave DATA_DIR half-deleted while the manifest still references it.
  const chunkSource = renderChunkModule(chunk);
  const manifestSource = renderManifest();
  const metaSource = `${JSON.stringify(meta, null, 2)}\n`;

  await rm(DATA_DIR, { recursive: true, force: true });
  await mkdir(DATA_DIR, { recursive: true });
  await mkdir(SOURCE_DIR, { recursive: true });

  await writeFile(new URL(`${NEUTRAL_LOCALE}.js`, DATA_DIR), chunkSource, "utf8");
  await writeFile(new URL("meta.json", DATA_DIR), metaSource, "utf8");
  await writeFile(MANIFEST_PATH, manifestSource, "utf8");

  const distinctNames = new Set(chunk.terms.map(entry => entry[1])).size;
  console.log(
    `Wrote ${chunk.terms.length} Pantone colours (${distinctNames} distinct names), `
    + `${(Buffer.byteLength(chunkSource, "utf8") / 1024).toFixed(0)} KB.`,
  );
}

if (import.meta.main) {
  await main();
}
