// Generated by scripts/sync-pantone. Do not edit by hand.
//
// Pantone Fashion, Home + Interiors (TCX/TPG) numbers, names and sRGB
// values from Margaret2/pantone-colors, which declares no licence and
// states that the names are Pantone copyright while the hex values are
// published freely on pantone.com.
//
// PANTONE is a trademark of Pantone LLC. This package is neither
// affiliated with nor endorsed by Pantone LLC.
import type { Chunk, ChunkLoaders } from "../../engine/types";

export const pantoneChunks: ChunkLoaders = {
  "und": () => import("../../data/pantone/und.js") as unknown as Promise<{ default: Chunk }>,
};
