import { mkdir, rm, writeFile } from "node:fs/promises";
import type { LanguageCoverage, PaletteChunk } from "../../src/engine/types";
import {
  ALIASES_QUERY,
  CATALOGUE_QUERY,
  ITEMS_QUERY,
  LABELS_QUERY,
  parseAliases,
  parseCatalogue,
  parseItems,
  parseLabels,
  runQuery,
  type Catalogue,
  type RawAliasRow,
  type RawCatalogueRow,
  type RawItemRow,
  type RawLabelRow,
} from "./fetch";
import {
  buildItems,
  buildPaletteChunk,
  catalogueMembership,
  inferCatalogueMembership,
  groupAliases,
  groupLabels,
  paletteCoverage,
  pruneCatalogueItems,
  stripCatalogueCodes,
  supportsLocaleCase,
} from "./transform";
import { unlistedScriptLetters } from "./scripts";

const DATA_DIR = new URL("../../src/data/wikidata/", import.meta.url);
const MANIFEST_PATH = new URL("../../src/sources/wikidata/chunks.ts", import.meta.url);

const ATTRIBUTION = [
  "// Generated by scripts/sync-wikidata. Do not edit by hand.",
  "//",
  "// Colour names derived from Wikidata (https://www.wikidata.org/), items whose",
  "// instance-of/subclass-of chain reaches Q1075 (colour) and which carry a P465",
  "// sRGB hex triplet.",
  "//",
  "// Wikidata content is released under CC0-1.0.",
];

export interface SyncMeta {
  source: "wikidata";
  retrievedAt: string;
  /** Catalogue size — the denominator every coverage figure is computed against. */
  itemCount: number;
  languages: Record<string, LanguageCoverage>;
}

export interface SyncOutput {
  chunks: Map<string, PaletteChunk>;
  meta: SyncMeta;
  /** Items that carried more than one best-rank hex, for the sync report. */
  multiHexItems: string[];
  /** Count of (locale, name) pairs claimed by more than one item. */
  collisions: number;
  /** Code-shaped labels removed, per catalogue. */
  catalogueDropped: Record<Catalogue, number>;
  /** Descriptive labels on catalogue items that were kept, e.g. `Verkehrsrot`. */
  catalogueSpared: number;
  /** Catalogue items Wikidata left unclassified, recognised by their labels. */
  inferredCatalogueItems: string[];
  /** Locale -> names the alphabet check removed, in upstream spelling. */
  droppedByScript: Record<string, string[]>;
  /** Letters in no listed script: the script table's blind spot, as a number. */
  unlistedLetters: number;
  /** Locales whose tag `Intl` rejects, folded by the invariant rule instead. */
  invariantCaseLocales: string[];
}

/**
 * Takes raw rows rather than grouped structures for two reasons: only the raw
 * rows still show which items carried more than one hex (`buildItems` collapses
 * them), and a single entry point means the sync report and the tests exercise
 * exactly the same pipeline.
 */
export function buildOutput(
  itemRows: readonly RawItemRow[],
  labelRows: readonly RawLabelRow[],
  aliasRows: readonly RawAliasRow[],
  catalogueRows: readonly RawCatalogueRow[],
  retrievedAt: string,
): SyncOutput {
  const membership = catalogueMembership(catalogueRows);
  // Wikidata leaves some catalogue items unclassified: Q35827305 is labelled
  // `RAL 9002` in eight languages but carries only the generic colour class,
  // so the membership query cannot see it. Inferring from the label first
  // means pruning, counting and the report all treat it like any other
  // catalogue item.
  const inferredCatalogueItems = inferCatalogueMembership(membership, labelRows);

  const splitLabels = stripCatalogueCodes(labelRows, membership);
  const splitAliases = stripCatalogueCodes(aliasRows, membership);

  const catalogueDropped: Record<Catalogue, number> = { pantone: 0, ral: 0, ncs: 0 };
  for (const row of [...splitLabels.dropped, ...splitAliases.dropped]) {
    const catalogue = membership.get(row.qid);
    if (catalogue !== undefined) catalogueDropped[catalogue]++;
  }

  // A catalogue item that kept a descriptive label in some language is still a
  // colour this source names, so it stays in the denominator. One that lost
  // every label would otherwise inflate every coverage figure.
  const survivingQids = new Set(splitLabels.kept.map(row => row.qid));
  const catalogueSpared = [...survivingQids].filter(qid => membership.has(qid)).length;

  const items = buildItems(pruneCatalogueItems(itemRows, membership, survivingQids));
  const labels = groupLabels(splitLabels.kept);
  const aliases = groupAliases(splitAliases.kept);

  let unlistedLetters = 0;
  for (const row of splitLabels.kept) unlistedLetters += unlistedScriptLetters(row.value);

  const hexesByQid = new Map<string, Set<string>>();
  for (const row of itemRows) {
    const bucket = hexesByQid.get(row.qid);
    if (bucket === undefined) hexesByQid.set(row.qid, new Set([row.hex]));
    else bucket.add(row.hex);
  }
  const multiHexItems = [...hexesByQid]
    .filter(([, values]) => values.size > 1)
    .map(([qid]) => qid)
    .sort();

  const chunks = new Map<string, PaletteChunk>();
  const languages: Record<string, LanguageCoverage> = {};
  const droppedByScript: Record<string, string[]> = {};
  const invariantCaseLocales: string[] = [];
  let collisions = 0;

  for (const [lang, labelMap] of labels) {
    const built = buildPaletteChunk(lang, items, labelMap, aliases.get(lang) ?? []);
    const chunk = built.chunk;
    if (built.droppedByScript.length > 0) droppedByScript[lang] = built.droppedByScript;
    if (!supportsLocaleCase(lang)) invariantCaseLocales.push(lang);

    // A locale whose every labelled item fell outside the catalogue would
    // produce a chunk that can answer nothing; don't ship one.
    if (chunk.terms.length === 0) continue;

    const occurrences = new Map<string, number>();
    for (const entry of chunk.terms) {
      occurrences.set(entry[0], (occurrences.get(entry[0]) ?? 0) + 1);
    }
    for (const count of occurrences.values()) {
      if (count > 1) collisions++;
    }

    chunks.set(lang, chunk);
    languages[lang] = paletteCoverage(chunk, items.length);
  }

  // `languages` is built by iterating `labels`, a Map whose insertion order
  // follows raw SPARQL row order (`LABELS_QUERY` has no `ORDER BY`). Without
  // sorting, an otherwise-unchanged re-sync would reshuffle the whole object
  // and produce a spuriously large diff in the generated `meta.json`.
  const sortedLanguages: Record<string, LanguageCoverage> = {};
  for (const lang of Object.keys(languages).sort()) {
    sortedLanguages[lang] = languages[lang]!;
  }

  return {
    chunks,
    meta: { source: "wikidata", retrievedAt, itemCount: items.length, languages: sortedLanguages },
    multiHexItems,
    collisions,
    catalogueDropped,
    catalogueSpared,
    inferredCatalogueItems,
    droppedByScript,
    unlistedLetters,
    // Sorted for the same reason `sortedLanguages` is: `labels` iterates in
    // raw SPARQL row order, so an unsorted list would reshuffle between
    // otherwise-identical syncs.
    invariantCaseLocales: invariantCaseLocales.sort(),
  };
}

export function renderChunkModule(chunk: PaletteChunk): string {
  return [...ATTRIBUTION, `export default ${JSON.stringify(chunk)};`, ""].join("\n");
}

export function renderManifest(locales: string[]): string {
  const entries = [...locales]
    .sort()
    .map(locale => (
      `  "${locale}": () => import("../../data/wikidata/${locale}.js") as unknown as Promise<{ default: Chunk }>,`
    ))
    .join("\n");

  return [
    ...ATTRIBUTION,
    "//",
    "// The chunk .js files below come from this same script's validated transform,",
    "// so asserting their shape here (rather than trusting allowJs inference, which",
    "// widens literal/tuple types) is honest and keeps the manifest type-checking.",
    "import type { Chunk, ChunkLoaders } from \"../../engine/types\";",
    "",
    "export const wikidataChunks: ChunkLoaders = {",
    entries,
    "};",
    "",
  ].join("\n");
}

export async function main(): Promise<void> {
  console.log("Querying Wikidata Query Service…");
  const [itemsJson, labelsJson, aliasesJson, catalogueJson] = await Promise.all([
    runQuery(ITEMS_QUERY),
    runQuery(LABELS_QUERY),
    runQuery(ALIASES_QUERY),
    runQuery(CATALOGUE_QUERY),
  ]);

  const itemRows = parseItems(itemsJson);
  const labelRows = parseLabels(labelsJson);
  const aliasRows = parseAliases(aliasesJson);
  const catalogueRows = parseCatalogue(catalogueJson);
  console.log(
    `  ${itemRows.length} item rows, ${labelRows.length} labels, `
    + `${aliasRows.length} aliases, ${catalogueRows.length} catalogue members`,
  );

  const output = buildOutput(itemRows, labelRows, aliasRows, catalogueRows, new Date().toISOString());

  // Render everything into memory before touching disk, so a rendering failure
  // cannot leave DATA_DIR half-deleted while the manifest still references it.
  const chunkSources = new Map<string, string>();
  for (const [lang, chunk] of output.chunks) chunkSources.set(lang, renderChunkModule(chunk));
  const manifestSource = renderManifest([...output.chunks.keys()]);
  const metaSource = `${JSON.stringify(output.meta, null, 2)}\n`;

  await rm(DATA_DIR, { recursive: true, force: true });
  await mkdir(DATA_DIR, { recursive: true });
  await mkdir(new URL("../../src/sources/wikidata/", import.meta.url), { recursive: true });

  let total = 0;
  for (const [lang, source] of chunkSources) {
    await writeFile(new URL(`${lang}.js`, DATA_DIR), source, "utf8");
    total += Buffer.byteLength(source, "utf8");
  }
  await writeFile(new URL("meta.json", DATA_DIR), metaSource, "utf8");
  await writeFile(MANIFEST_PATH, manifestSource, "utf8");

  const ranked = [...output.chunks.entries()].sort((a, b) => b[1].terms.length - a[1].terms.length);
  console.log(`\nWrote ${ranked.length} chunks, ${(total / 1024).toFixed(0)} KB total.`);
  console.log("Largest:");
  for (const [lang, chunk] of ranked.slice(0, 12)) {
    const coverage = output.meta.languages[lang]!.coverage;
    console.log(`  ${lang.padEnd(8)} ${String(chunk.terms.length).padStart(4)} terms  ${(coverage * 100).toFixed(1)}%`);
  }

  console.log(`\nCatalogue: ${output.meta.itemCount} items`);
  console.log(`Items with multiple hex values (lowest sorted value kept): ${output.multiHexItems.length}`);
  console.log(`Name collisions resolved by sitelink ranking: ${output.collisions}`);

  const { pantone, ral, ncs } = output.catalogueDropped;
  console.log(`\nCatalogue codes removed: ${pantone + ral + ncs} (pantone ${pantone}, ral ${ral}, ncs ${ncs})`);
  console.log(`Descriptive names kept on catalogue items: ${output.catalogueSpared}`);
  console.log(
    "Catalogue items Wikidata left unclassified, inferred from labels: "
    + `${output.inferredCatalogueItems.length}`,
  );

  const scriptDrops = Object.entries(output.droppedByScript);
  const scriptTotal = scriptDrops.reduce((sum, [, names]) => sum + names.length, 0);
  console.log(`\nDropped by the alphabet check: ${scriptTotal}`);
  for (const [lang, names] of scriptDrops.sort((a, b) => b[1].length - a[1].length)) {
    console.log(`  ${lang.padEnd(9)} ${names.join(" · ")}`);
  }

  console.log(`\nLetters in no listed script: ${output.unlistedLetters}`);
  if (output.invariantCaseLocales.length > 0) {
    console.log(`Locales folded by the invariant rule: ${output.invariantCaseLocales.join(", ")}`);
  }
  console.log(`Retrieved at: ${output.meta.retrievedAt}`);
}

if (import.meta.main) {
  await main();
}
