import { mkdir, rm, writeFile } from "node:fs/promises";
import type { LanguageCoverage, PaletteChunk } from "../../src/engine/types";
import { fetchRalClassic } from "./fetch";
import { NEUTRAL_LOCALE, buildRalChunk } from "./transform";

const DATA_DIR = new URL("../../src/data/ral/", import.meta.url);
const SOURCE_DIR = new URL("../../src/sources/ral/", import.meta.url);
const MANIFEST_PATH = new URL("chunks.ts", SOURCE_DIR);

const ATTRIBUTION = [
  "// Generated by scripts/sync-ral. Do not edit by hand.",
  "//",
  "// RAL Classic codes and sRGB values from ieskudero/ral-colors (MIT).",
  "//",
  "// RAL is a trademark of RAL gGmbH. These are factual colour values, not",
  "// the RAL system itself, and this package is neither affiliated with nor",
  "// endorsed by RAL gGmbH.",
];

export interface RalMeta {
  source: "ral";
  retrievedAt: string;
  itemCount: number;
  languages: Record<string, LanguageCoverage>;
}

export function buildMeta(chunk: PaletteChunk, retrievedAt: string): RalMeta {
  return {
    source: "ral",
    retrievedAt,
    itemCount: chunk.terms.length,
    // A catalogue names its own catalogue entirely, so coverage is 1 by
    // construction rather than a measured fraction.
    languages: { [NEUTRAL_LOCALE]: { model: "palette", terms: chunk.terms.length, coverage: 1 } },
  };
}

export function renderChunkModule(chunk: PaletteChunk): string {
  return [...ATTRIBUTION, `export default ${JSON.stringify(chunk)};`, ""].join("\n");
}

export function renderManifest(): string {
  return [
    ...ATTRIBUTION,
    "import type { Chunk, ChunkLoaders } from \"../../engine/types\";",
    "",
    "export const ralChunks: ChunkLoaders = {",
    `  "${NEUTRAL_LOCALE}": () => import("../../data/ral/${NEUTRAL_LOCALE}.js") as unknown as Promise<{ default: Chunk }>,`,
    "};",
    "",
  ].join("\n");
}

export async function main(): Promise<void> {
  console.log("Fetching RAL Classic data…");
  const rows = await fetchRalClassic();
  const chunk = buildRalChunk(rows);
  const meta = buildMeta(chunk, new Date().toISOString());

  // Render everything into memory before touching disk, so a rendering failure
  // cannot leave DATA_DIR half-deleted while the manifest still references it.
  const chunkSource = renderChunkModule(chunk);
  const manifestSource = renderManifest();
  const metaSource = `${JSON.stringify(meta, null, 2)}\n`;

  await rm(DATA_DIR, { recursive: true, force: true });
  await mkdir(DATA_DIR, { recursive: true });
  await mkdir(SOURCE_DIR, { recursive: true });

  await writeFile(new URL(`${NEUTRAL_LOCALE}.js`, DATA_DIR), chunkSource, "utf8");
  await writeFile(new URL("meta.json", DATA_DIR), metaSource, "utf8");
  await writeFile(MANIFEST_PATH, manifestSource, "utf8");

  console.log(
    `Wrote ${chunk.terms.length} RAL Classic codes, `
    + `${(Buffer.byteLength(chunkSource, "utf8") / 1024).toFixed(0)} KB.`,
  );
}

if (import.meta.main) {
  await main();
}
