name: Publish urcolor

on:
  push:
    branches: [main]
    paths:
      - 'packages/urcolor/package.json'

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      package-dir: 'packages/urcolor'
      package-name: 'urcolor'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
