name: Publish @urcolor/angular

on:
  push:
    branches: [main]
    paths:
      - 'packages/angular/package.json'

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      package-dir: 'packages/angular'
      package-name: '@urcolor/angular'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
