name: Publish @urcolor/relative

on:
  push:
    branches: [main]
    paths:
      - 'packages/relative/package.json'

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      package-dir: 'packages/relative'
      package-name: '@urcolor/relative'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
