name: Publish @urcolor/core

on:
  push:
    branches: [main]
    paths:
      - 'packages/core/package.json'

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      package-dir: 'packages/core'
      package-name: '@urcolor/core'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
