name: Publish @urcolor/svelte

on:
  push:
    branches: [main]
    paths:
      - 'packages/svelte/package.json'

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      package-dir: 'packages/svelte'
      package-name: '@urcolor/svelte'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
