name: Publish @urcolor/vue

on:
  push:
    branches: [main]
    paths:
      - 'packages/vue/package.json'

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      package-dir: 'packages/vue'
      package-name: '@urcolor/vue'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
