name: Publish @urcolor/i18n

on:
  push:
    branches: [main]
    paths:
      - 'packages/i18n/package.json'

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      package-dir: 'packages/i18n'
      package-name: '@urcolor/i18n'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
