name: Publish @urcolor/primitives

on:
  push:
    branches: [main]
    paths:
      - 'packages/primitives/package.json'

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      package-dir: 'packages/primitives'
      package-name: '@urcolor/primitives'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
